name: Stream Builder

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıklar
        run: |
          pip install --upgrade pip
          pip install flask requests beautifulsoup4 yt-dlp

      - name: Script çalıştır
        env:
          GITHUB_ACTIONS: true
        run: |
          python status_md.py
