name: Update m3u8

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: yt-dlp kurulumu
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: common.py çalıştır
        run: python common.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.m3u8 || true
          git commit -m "Update playlist" || echo "No changes"
          git push
