name: Dizipaluk

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Kur
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps

      - name: Botu Çalıştır
        run: python dizipaluk.py

      - name: Veriyi GitHub'a Pushla
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          # Sadece dosya varsa ekle (hata vermemesi için)
          if [ -f filmler.json ]; then
            git add filmler.json
            git commit -m "Güncel film listesi: $(date)" || echo "Değişiklik yok"
            git push
          else
            echo "Dosya oluşmadı, pushlanacak bir şey yok."
          fi
