name: Otomatik Film/Dizi Güncelleyici (SUSS HDF)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Yükle (curl_cffi Temiz Kurulum)
      run: |
        python -m pip install --upgrade pip
        # Önbellek kullanmadan ve en güncel bağımlılıklarla kurulum yapıyoruz
        pip install --no-cache-dir curl_cffi

    - name: Botu Çalıştır
      run: |
        python hdf/hdf.py

    - name: Değişiklikleri GitHub'a Geri Yükle
      run: |
        git config --global user.name "GitHub Otomasyonu"
        git config --global user.email "actions@github.com"
        git add hdf/data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Güncel HDF Film/Dizi Verileri Eklendi" && git push)
